all: docs

MAIN = .
TEXDIR = ${MAIN}/tex
LOGODIR = ${MAIN}/logos
IMGDIR = ${MAIN}/images
DIADIR = ${MAIN}/diagrams

TEXFILES = ${MAIN}/BrainGrid_Documentation.tex \
			${TEXDIR}/abstract.tex \
			${TEXDIR}/acknowledgements.tex \
			${TEXDIR}/faq.tex \
			${TEXDIR}/features.tex \
			${TEXDIR}/implement-other-models.tex \			
			${TEXDIR}/lif-model.tex \
			${TEXDIR}/simulation-design.tex \
			${TEXDIR}/tools.tex \
			${TEXDIR}/user-guide.tex 

docs:


