/**
 * @brief A leaky-integrate-and-fire (I&F) neural network model.
 *
 * @class  SingleThreadedSpikingModel SingleThreadedSpikingModel.h "SingleThreadedSpikingModel.h"
 *
 * Implements both neuron and synapse behaviour.
 *
 * A standard leaky-integrate-and-fire neuron model is implemented
 * where the membrane potential \f$V_m\f$ of a neuron is given by
 * \f[
 *   \tau_m \frac{d V_m}{dt} = -(V_m-V_{resting}) + R_m \cdot (I_{syn}(t)+I_{inject}+I_{noise})
 * \f]
 * where \f$\tau_m=C_m\cdot R_m\f$ is the membrane time constant,
 * \f$R_m\f$ is the membrane resistance, \f$I_{syn}(t)\f$ is the
 * current supplied by the synapses, \f$I_{inject}\f$ is a
 * non-specific background current and \f$I_{noise}\f$ is a
 * Gaussian random variable with zero mean and a given variance
 * noise.
 *
 * At time \f$t=0\f$ \f$V_m\f$ is set to \f$V_{init}\f$. If
 * \f$V_m\f$ exceeds the threshold voltage \f$V_{thresh}\f$ it is
 * reset to \f$V_{reset}\f$ and hold there for the length
 * \f$T_{refract}\f$ of the absolute refractory period.
 *
 * The exponential Euler method is used for numerical integration.
 * The main idea behind the exponential Euler rule is that many biological 
 * processes are governed by an exponential decay function.
 * For an equation of the form:
 * \f[
 *  \frac{d y}{dt} = A - By
 * \f]
 *
 * its scheme is given by:
 * \f[
 *  y(t+\Delta t) = y(t) \cdot \mathrm{e}^{-B \Delta t} + \frac{A}{B} \cdot (1 - \mathrm{e}^{-B \Delta t})
 * \f]
 *
 * After appropriate substituting all variables, we obtain the exponential Euler step:
 * \f[
 *  V_m(t+\Delta t) = V_m(t) \cdot \mathrm{e}^{-\frac{\Delta t}{\tau_m}} + 
 *  R_m \cdot (I_{syn}(t)+I_{inject}+I_{noise}+\frac{V_{resting}}{R_m}) 
 *  \cdot (1 - \mathrm{e}^{-\frac{\Delta t}{\tau_m}})
 * \f]
 *
 * Phenomenological model of frequency-dependent synapses exibit dynamics that include
 * activity-dependent facilitation and depression (Tsodyks and Markram 1997, Tsodyks et al. 1998). 
 * The model has two state variables: \f$r\f$ (the fraction of available synaptic efficacy), and
 * \f$u\f$ (the running value of utilization of synaptic efficacy).
 *
 * \f[
 *  r_{n+1} = r_n \cdot (1-u_{n+1}) \cdot \mathrm{e}^{-\frac{\Delta t}{\tau_{rec}}} +
 *  1 - \mathrm{e}^{-\frac{\Delta t}{\tau_{rec}}}
 * \f]
 *
 * \f[
 * \f]
 *
 * where \f$\Delta t\f$ is the time interval between nth and (n + 1)th AP,
 * the two time constants \f$\tau_{rec}\f$ and \f$\tau_{facil}\f$ govern recovery from depression,
 * and facilitation after a spike, and \f$U\f$ is utilization of synaptic efficacy (Markram et al. 1998).
 *
 * The synaptic response that is generated by any AP in a train is therefore given by:
 * \f[
 *  EPSP_n = A \cdot r_n \cdot u_n
 * \f]
 *
 * This model is a rewrite of work by Stiber, Kawasaki, Allan Ortiz, and Cory Mayberry
 *
 * @authors Derek McLean
 */

#pragma once

#include "Model.h"

class SingleThreadedSpikingModel : public Model {

public:
	//Constructor & Destructor
	SingleThreadedSpikingModel(Connections *conns, AllNeurons *neurons, AllSynapses *synapses, Layout *layout);
	virtual ~SingleThreadedSpikingModel();

	virtual void advance(const SimulationInfo *sim_info);
	virtual void updateConnections(const int currentStep, const SimulationInfo *sim_info, IRecorder* simRecorder);

	/* -----------------
	* # Helper Functions
	* ------------------
	*/

	// TODO
	void preSpikeHit(AllSynapses &synapses,  const uint32_t iSyn);

	// Helper for #advanceSynapses. Updates state of a single synapse.
	void advanceSynapse(AllSynapses &synapses, const uint32_t iSyn, const BGFLOAT deltaT);

protected:
	// Initiates a firing of a neuron to connected neurons
	virtual void fire(AllNeurons &neurons, const int index, const BGFLOAT deltaT) const;

private:
	// # Advance Network/Model
	// -----------------------

	// Update the state of all neurons for a time step
	void advanceNeurons(AllNeurons& neurons, AllSynapses &synapses, const SimulationInfo *sim_info);
	// Helper for #advanceNeuron. Updates state of a single neuron.
	virtual void advanceNeuron(AllNeurons& neurons, const int index, const BGFLOAT deltaT) = 0;

	// Update the state of all synapses for a time step
	void advanceSynapses(const int num_neurons, AllSynapses &synapses, const BGFLOAT deltaT);

	// TODO
	bool isSpikeQueue(AllSynapses &synapses, const uint32_t iSyn);

	// # Update Connections
	// --------------------

	// TODO
	void updateWeights(const int num_neurons, AllNeurons &neurons, AllSynapses &synapses, const SimulationInfo *sim_info);

	// TODO
	void eraseSynapse(AllSynapses &synapses, const int neuron_index, const uint32_t iSyn);
	// TODO
	void addSynapse(AllSynapses &synapses, synapseType type, const int src_neuron, const int dest_neuron, Coordinate &source, Coordinate &dest, BGFLOAT *sum_point, const BGFLOAT deltaT);

	// -----------------------------------------------------------------------------------------
	// # Generic Functions for handling synapse types
	// ---------------------------------------------

	// Determines the type of synapse for a synapse at a given location in the network.
	synapseType synType(AllNeurons &neurons, Coordinate src_coord, Coordinate dest_coord, const int width);
	// Determines the type of synapse for a synapse between two neurons.
	synapseType synType(AllNeurons &neurons, const int src_neuron, const int dest_neuron);
	// Determines the direction of the weight for a given synapse type.
	int synSign(const synapseType t);

};




